name: "CMake"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

env:
  VCPKG_FEATURE_FLAGS: "manifests,binarycaching,registries"

jobs:
  macos13:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0.2"
      - name: "Setup metal-cpp"
        run: ./setup-metal-cpp.ps1 -Folder "externals" -FileName "metal-cpp_macOS15.2_iOS18.2.zip"
        shell: pwsh
      - uses: lukka/get-cmake@v4.0.0
        with:
          cmakeVersion: "~4.0.0"
      - uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: "${{ runner.tool_cache }}/vcpkg"
          vcpkgGitCommitId: b02e341c927f16d991edbd915d8ea43eac52096c # 2025.03.19
          vcpkgJsonGlob: "**/vcpkg.json"
          vcpkgConfigurationJsonGlob: "**/vcpkg-configuration.json"
          runVcpkgInstall: true
      - uses: lukka/run-cmake@v10.7
        with:
          configurePreset: "x64-osx"
          buildPreset: "x64-osx-debug"
          testPreset: "x64-osx-debug"
