name: "Swift"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  swiftpm:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: "15.2.0"
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0.2"
      - uses: ConorMacBride/install-package@v1.1.0
        with:
          brew: swiftlint
      - name: "Setup metal-cpp"
        run: ./setup-metal-cpp.ps1 -Folder "externals" -FileName "metal-cpp_macOS15.2_iOS18.2.zip"
        shell: pwsh
      - name: "Swift Build(Debug)"
        run: swift build --configuration debug # --verbose --target ...
      - name: "Swift Build(Release)"
        run: swift build --configuration release
      - name: "Swift Test"
        run: swift test --verbose --enable-code-coverage
      - name: "Swift Lint"
        run: swiftlint lint --output docs/lint.md --reporter markdown # --autocorrect
